default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: hospital_app_development

test:
  <<: *default
  database: hospital_app_development_test

production:
  <<: *default
